import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter, Vazirmatn } from "next/font/google";
import "./globals.css";
// import NavbarPage from "@/components/UiComponend/navbar";
import NavebarPage from "@/components/shared/navbar";

const inter = Inter({
  variable: "--font-Inter",
  subsets: ["latin"],
});

const vazirmtn = Vazirmatn({
  variable: "--font-Vazirmtn",
  subsets: ["latin"],
});

export const metadata: Metadata = {

  title :{
    default :"همه کالا",
    template : "%s | همه کالا",
    absolute : "همه کالا"
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${vazirmtn.className} ${inter.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <NavebarPage/>
        {children}</body>
    </html>
  );
}
